<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QZ-LT-R-CTK-023" failures="1" tests="3" name="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework" time="68.095" errors="0" timestamp="12 Nov 2024 06:38:49 GMT" skipped="1">
  <testcase classname="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework" name="logInPage" time="18.861">
    <skipped/>
  </testcase> <!-- logInPage -->
  <testcase classname="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework" name="logInPage" time="27.206">
    <failure message="expected [Incorrect email or password.] but found [Incorrect email  password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at End_To_End_SeleniumFramework.Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework.logInPage(Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- logInPage -->
  <testcase classname="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework" name="productCatalog" time="22.028"/>
</testsuite> <!-- End_To_End_SeleniumFramework.Code9IRetryAnalyzerToReeunTheFlakyFailedSeleniumTestsInFramework -->
